### PR TITLE
Revert/7.2 get service cors [S3C-1009]

### PR DESCRIPTION
**Pull request by electrachong**
Depends on https://github.com/scality/Arsenal/pull/384

### CODE REVIEW

**Comment by electrachong** [comment]
@ironman-machine 
SCALITY_ARSENAL_BRANCH=revert/7.2-getService-cors
try

**Comment by rahulreddy** [comment]
@ironman-machine 
after=https://github.com/scality/Arsenal/pull/384
r=3e1b5ca87d37eb15f55ecc4b8eaf867dcc887f4c

**Comment by rahulreddy** [comment]
@ironman-machine r-

**Comment by rahulreddy** [comment]
@ironman-machine
clean
after=scality/Arsenal#384
r=3e1b5ca87d37eb15f55ecc4b8eaf867dcc887f4c

**Comment by electrachong** [comment]
rebased; end to end running here: http://ci.ironmann.io/gh/scality/Integration/17726

**Comment by electrachong** [comment]
@ironman-machine 
clean
after=scality/Arsenal#384
r=fe365da09fb45280755b796b5f611da1bc1b3721

**Comment by electrachong** [comment]
@ironman-machine
clean
after=scality/Arsenal#384
r=fe365da09fb45280755b796b5f611da1bc1b3721

**Comment by electrachong** [comment]
@ironman-machine
r-
clean
after=scality/Arsenal#384
r=fe365da09fb45280755b796b5f611da1bc1b3721

**Comment by electrachong** [comment]
http://ci.ironmann.io/gh/scality/Integration/17740 and http://ci.ironmann.io/gh/scality/Integration/17726 passed; merging manually

**Comment by electrachong** [comment]
@ironman-machine
r-
clean
after=scality/Arsenal#384

**Comment by electrachong** [comment]
@ironman-machine r+

**Pull request merged**
