### PR TITLE
S3C-1111 COPY to restore version of object is not working

### PR DESCRIPTION
**Pull request by nicolas2bert**

### CODE REVIEW

**Comment by nicolas2bert** [comment]
@ironman-machine r+

**Comment by nicolas2bert** [comment]
@ironman-machine r+

**Comment by nicolas2bert** [comment]
@ironman-machine r+

**Comment by nicolas2bert** [comment]
@ironman-machine r+

**Comment by DeepDiver1975** [comment]
Thanks a lot @nicolas2bert for the fix. Any planned date to bring this to the docker images on https://hub.docker.com/r/scality/s3server/

THX a lot!

**Pull request merged**
