### PR TITLE
Ft/use arsenal extension

### PR DESCRIPTION
**Pull request by DavidPineauScality**
This PR updates slightly the use of the listing algorithms from Arsenal, to synchronize the project with scality/Arsenal#99

### CODE REVIEW

**Comment by DavidPineauScality** [comment]
@ironman-machine please validate :)
SCALITY_METADATA_BRANCH=ft/useArsenalExtension

**Comment by MathieuCassagne** [comment]
LGTM :+1:

**Comment by LaurenSpiegel** [comment]
👍

**Comment by DavidPineauScality** [comment]
@ironman-machine again :)

**Comment by DavidPineauScality** [comment]
restarted functests in CI since I updated the Arsenal branch :)

**Comment by DavidPineauScality** [comment]
merging on behalf or @LaurenSpiegel, in order to merge this in synchro with Arsenal#99

**Pull request merged**
