### PR TITLE
FX: Checks multiObjectDelete Empty Case

### PR DESCRIPTION
**Pull request by alexanderchan-scality**
S3C-1063 
Adds a check to handle cases in which multiObjectDelete is passed an empty list

### CODE REVIEW

**Comment by JianqinWang** [comment]
Should there be tests for this?

**Comment by alexanderchan-scality** [comment]
@ironman-machine r+

**Comment by alexanderchan-scality** [comment]
@ironman-machine try

**Comment by LaurenSpiegel** [comment]
@ironman-machine r+

**Pull request merged**
