### PR TITLE
fx: use core querysting instead of qs module

### PR DESCRIPTION
**Pull request by alexanderchan-scality**
Includes S3 PR https://github.com/scality/S3/pull/1167

### CODE REVIEW

**Comment by alexanderchan-scality** [comment]
@ironman-machine 
DEFAULT_BRANCH=rel/7.4
try

**Comment by JianqinWang** [comment]
@alexanderchan-scality was the dependency in `package.json` removed in a different pr and this is a follow-up fix?

**Comment by alexanderchan-scality** [comment]
@ploki yeah. Another S3 dep. has `qs` as one of its dependencies, so this missing `qs` dep wasn't flagged as an error. `querystring` is used instead since it is one of the core nodejs modules.
@JianqinWang `qs` dep wasn't added, I had missed it due to the reasons above.

**Comment by jeremyds** [comment]
I guess it has an impact on https://github.com/scality/scality-nfsd/pull/114 right?

**Comment by alexanderchan-scality** [comment]
@ironman-machine 
DEFAULT_BRANCH=rel/7.4
try

**Comment by alexanderchan-scality** [comment]
Passing E2E: http://ci.ironmann.io/gh/scality/Integration/20536

**Comment by alexanderchan-scality** [comment]
@ironman-machine
DEFAULT_BRANCH=rel/7.4
try

**Comment by alexanderchan-scality** [comment]
@ironman-machine
DEFAULT_BRANCH=rel/7.4
try

**Comment by alexanderchan-scality** [comment]
passing e2e: ci.ironmann.io/gh/scality/Integration/20561

**Pull request merged**
