### PR TITLE
Centralize model version tracking for BucketInfo

### PR DESCRIPTION
**Pull request by LaurenSpiegel**
We are manually updating the BucketInfo model version a number of places in the code where BucketInfo is instantiated.  This is likely to be forgotten when changes are made to the BucketInfo model.  So, I have created a static function on the BucketInfo class which pulls the current model version.  I also added a changelog to keep track of the versions.

### CODE REVIEW

**Comment by rahulreddy** [comment]
👍 

Two minor things.

- Do you mind adding the PR description to the commit body as a summary?
- Use FT tag for the commit message

**Comment by LaurenSpiegel** [comment]
updated.

**Comment by LaurenSpiegel** [comment]
@ironman-machine check it out

**Comment by LaurenSpiegel** [comment]
end to end passed

**Comment by alexandre-merle** [comment]
LGTM :+1: and rebased

**Comment by alexandre-merle** [comment]
Merging on behalf of @LaurenSpiegel

**Pull request merged**
