### PR TITLE
Use refactored Arsenal's Auth API - Step 1

### PR DESCRIPTION
**Pull request by DavidPineauScality**
This is the first step towards using the cleaned-up Auth API from arsenal.
The work is still ongoing, but this will allow us to avoid falling out-of-sync.

Depends on: https://github.com/scality/Arsenal/pull/119 then https://github.com/scality/vaultclient/pull/94

### CODE REVIEW

**Comment by alexandre-merle** [comment]
The vault backend in lib/auth/vault.js is not updated to reflect the changes here, was update on the file inside arsenal, but it's the wrong one

**Comment by AntoninCoulibaly** [comment]
updated

**Comment by AntoninCoulibaly** [comment]
@ironman-machine 

SCALITY_VAULT_BRANCH=dev/cleanup/AuthAPI-Step1

**Comment by michael-zapata** [comment]
:+1:

**Pull request merged**
