### PR TITLE
FIX: put Bucket as a user

### PR DESCRIPTION
**Pull request by nicolas2bert**
FIXES: #704

### CODE REVIEW

**Comment by LaurenSpiegel** [comment]
let's add a functional test like we do for multi-object delete from a user but with bucket put

**Comment by nicolas2bert** [comment]
@ironman-machine try

**Comment by nicolas2bert** [comment]
@ironman-machine ok

**Comment by nicolas2bert** [comment]
@ironman-machine debug

**Comment by nicolas2bert** [comment]
@ironman-machine ok

**Comment by nicolas2bert** [comment]
@ironman-machine ok

**Pull request merged**
