### PR TITLE
Fwd/6.4 7.2

### PR DESCRIPTION
**Pull request by flavien-scality**

### CODE REVIEW

**Comment by flavien-scality** [comment]
@ironman-machine 
SCALITY_ARSENAL_BRANCH=bugfix/S3C-1026-S3-consumes-too-much-tcp-memory
try

**Comment by rahulreddy** [comment]
@ironman-machine clean r+

**Comment by rahulreddy** [comment]
@ironman-machine r-

**Comment by rahulreddy** [comment]
http://ci.ironmann.io/gh/scality/Integration/19582 passed

**Pull request merged**
