### PR TITLE
Fwdport 6.2.1 6.2.5

### PR DESCRIPTION
**Pull request by DavidPineauScality**

### CODE REVIEW

**Comment by DavidPineauScality** [comment]
E2E launched from https://github.com/scality/Integration/pull/348

**Comment by DavidPineauScality** [comment]
E2E passed on the Integration PR just now. whenever both PRs are reviewed, we'll merge S3's PR directly followed by the merge of Integration's PR through ultron

**Comment by LaurenSpiegel** [comment]
@DavidPineauScality, will you please update the forward port to include the other 6.2.1 changes?

**Comment by DavidPineauScality** [comment]
@LaurenSpiegel Updating a forward port is very similar to "re-making" it. As such, I'd rather make a new forward port after this one, since it is now mergeable.

**Comment by DavidPineauScality** [comment]
Merging on behalf of @LaurenSpiegel (due to synchronicity requirements with scality/Integration#348

**Pull request merged**
