### PR TITLE
FT: Add remaining Utapi listing levels

### PR DESCRIPTION
**Pull request by bennettbuchanan**
Add options to list user and service level metrics.

### CODE REVIEW

**Comment by rahulreddy** [comment]
@ironman-machine

**Comment by rahulreddy** [comment]
@ironman-machine try

**Comment by bennettbuchanan** [comment]
@ironman-machine try

**Comment by bennettbuchanan** [comment]
@ironman-machine

**Comment by bennettbuchanan** [comment]
@ironman-machine try

**Comment by bennettbuchanan** [comment]
E2E passed.

**Pull request merged**
