### PR TITLE
Allow CORS headers for get service

### PR DESCRIPTION
**Pull request by vrancurel**
- allow and return headers in preflight for get service
- add cors headers in get service

### CODE REVIEW

**Comment by LaurenSpiegel** [comment]
@electrachong to finish and write tests

**Comment by electrachong** [comment]
@ironman-machine 
SCALITY_ARSENAL_BRANCH=ft/S3C-878/allowCorsForGetService
try

**Comment by electrachong** [comment]
@ironman-machine 
SCALITY_ARSENAL_BRANCH=ft/S3C-878/allowCorsForGetService
try

**Comment by electrachong** [comment]
a replication test failed; end-to-end retried here: http://ci.ironmann.io/gh/scality/Integration/14913

**Comment by electrachong** [comment]
you can do it Jarvis, I believe in you

@ironman-machine
SCALITY_ARSENAL_BRANCH=ft/S3C-878/allowCorsForGetService
try

**Comment by electrachong** [comment]
end-to-end failed for unrelated reasons (flaky replication test)

**Comment by dora-korpar** [comment]
Isn't the associated Arsenal PR on hold atm?

**Comment by electrachong** [comment]
@dora-korpar not that I'm aware of? https://github.com/scality/Arsenal/pull/340

**Comment by dora-korpar** [comment]
was thinking of a different one heh ^^

**Comment by dora-korpar** [comment]
@ironman-machine r+

**Comment by dora-korpar** [comment]
sorry jarvis

**Comment by electrachong** [comment]
r+

**Comment by electrachong** [comment]
@ironman-machine r+

**Pull request merged**
