### PR TITLE
S3C-1115 FT: GCP Bucket APIs

### PR DESCRIPTION
**Pull request by alexanderchan-scality**
Implements GCP Bucket GET/PUT/DELETE/HEAD APIs
Review only: 4d6c350ddb67b59a7d3a22f963067d05ef3135d6

Reference Docs:
HEAD API: https://cloud.google.com/storage/docs/xml-api/head-bucket
PUT API: https://cloud.google.com/storage/docs/xml-api/put-bucket-create
GET API: https://cloud.google.com/storage/docs/xml-api/get-bucket-list
DELETE API: https://cloud.google.com/storage/docs/xml-api/delete-bucket

### CODE REVIEW

**Comment by alexanderchan-scality** [comment]
@ironman-machine try

**Comment by rahulreddy** [comment]
You can set this to master. Custom branches require Ultron support otherwise.

**Comment by alexanderchan-scality** [comment]
@ironman-machine try

**Comment by rahulreddy** [comment]
@ironman-machine try

**Comment by alexanderchan-scality** [comment]
@ironman-machine try

**Pull request closed without merging**
