### PR TITLE
Only new metadata stored when obj put overwrite

### LINKED ISSUE #126: Mixed metadata on object put override
When putting an object with the same key, we are not overwriting all user metadata if the new user metadata and the old user metadata do not have the same keys.

### PR DESCRIPTION
**Pull request by LaurenSpiegel**
This closes #126.

### CODE REVIEW

**Comment by LaurenSpiegel** [comment]
@ironman-machine work to do...

**Comment by rahulreddy** [comment]
👍 
Please add BF tag to the commit before you merge.

**Comment by LaurenSpiegel** [comment]
@ironman-machine try that again

**Comment by alexandre-merle** [comment]
LGTM :+1:

**Pull request merged**
