### PR TITLE
BF: Pass prev. size to utapi on object overwrite

### PR DESCRIPTION
**Pull request by rahulreddy**
Utapi needs both previous and new content-length of the object that is being overwritten to calculate storage utilized and bandwidth for the bucket

### CODE REVIEW

**Comment by LaurenSpiegel** [comment]
👍

**Comment by nicolas2bert** [comment]
👍

**Comment by rahulreddy** [comment]
@ironman-machine test please

**Comment by rahulreddy** [comment]
End to end passed!

**Pull request merged**
