### PR TITLE
forward port rel/7.0 into rel/7.1

### PR DESCRIPTION
**Pull request by electrachong**
Depends on https://github.com/scality/Integration/pull/616

### CODE REVIEW

**Comment by electrachong** [comment]
@ironman-machine try

**Comment by electrachong** [comment]
@ironman-machine 
SCALITY_INTEGRATION_BRANCH=forward/rel/7.0
try

**Comment by rahulreddy** [comment]
@ironman-machine 
after=https://github.com/scality/Integration/pull/616
r+

**Comment by rahulreddy** [comment]
@ironman-machine clean r+

**Comment by rahulreddy** [comment]
E2E passed here http://ci.ironmann.io/gh/scality/Integration/18044

**Pull request merged**
