### PR TITLE
fix MPU object GET + PartNumber

### PR DESCRIPTION
**Pull request by jonathan-gramain**
This fixes the range passed to setPartRanges() as an inclusive range.

Replaces https://github.com/scality/S3/pull/974.

### CODE REVIEW

**Comment by jonathan-gramain** [comment]
@ironman-machine 
SCALITY_ARSENAL_BRANCH=bf/S3C-1040-locations-max-issue
try

**Comment by jonathan-gramain** [comment]
See also sanity check added in https://github.com/scality/Arsenal/pull/365.

**Comment by jonathan-gramain** [comment]
@ironman-machine
SCALITY_ARSENAL_BRANCH=bf/S3C-1040-locations-max-issue
try

**Comment by jonathan-gramain** [comment]
E2E passed on master branch: http://ci.ironmann.io/gh/scality/Integration/16627#build-parameters

rel/7.1 failed due to another issue fixed in https://github.com/scality/backbeat/pull/127, waiting for test results.

**Comment by jonathan-gramain** [comment]
rel/7.1 branch passed in http://ci.ironmann.io/gh/scality/Integration/16632.

**Comment by rahulreddy** [comment]
@ironman-machine clean r+

**Comment by LaurenSpiegel** [comment]
end to end failed because of flakeyness.  merging.

**Pull request merged**
