### PR TITLE
[DO NOT REVIEW] test/failingLargeMpu

### PR DESCRIPTION
**Pull request by electrachong**
testing for issue https://github.com/scality/Integration/issues/449

### CODE REVIEW

**Comment by electrachong** [comment]
end-to-end: http://ci.ironmann.io/gh/scality/Integration/9377

**Comment by electrachong** [comment]
test we are concerned about passed, trying again to capture failure:
http://ci.ironmann.io/gh/scality/Integration/9381

**Comment by electrachong** [comment]
Last test resulted in failure, this was the message that was printed:
```
===========================
Cannot have more parts in complete message than were put
partLength (10000 > storedPartsAsObjects.length (4752)
===========================
```
Oddly though I also printed the entire storedPartsAsObjects length and it looks like it has the 10,000 different parts. Perplexing.

Here is the artifact: http://ci.ironmann.io/gh/scality/Integration/9381/artifacts/0/tmp/circle-artifacts.DRa1poS/docker-logs/scality-s3-node1.amazonaws.com/logs/s3-0.log

**Comment by electrachong** [comment]
So far:
first completeMpu request:
```
{“name":"S3","clientIP":"::ffff:172.17.0.2","clientPort":37030,"httpMethod":"POST","httpURL":"/bigmpu-test-bucket-1486497345481/mpuKey?uploadId=eee72e77c5bf451fbb42d21a6204217a","time":1486497681824,"req_id":"c3147cb276279110d561","level":"info","message":"received request","hostname":"box5","pid":122}
```

first object/part in completeMpu storedPartsAsObjects:
```
    {
        "key": "eee72e77c5bf451fbb42d21a6204217a..|..00001",
        "ETag": "\"900150983cd24fb0d6963f7d28e17f72\"",
        "size": 3,
        "locations": [
            {
                "key": "F6ED360FCBEDCBFCC286B16B87A3115957F99220",
                "dataStoreName": "sproxyd"
            }
        ]
    },
```
There are 10,000 parts, which is what we expect.

After storedPartsAsObjects is printed, we get maybe 10,000 of these:
```
{“name":"S3","bucketName":"bigmpu-test-bucket-1486497345481","objectKey":"mpuKey","bytesReceived":868993,"bodyLength":868993,"setting":"yes","time":1486497683116,"req_id":"c3147cb276279110d561","level":"info","message":"MPU_TESTING env variable setting","hostname":"box5","pid":122}
```
(same request)

However, no further logs with request id `c3147cb276279110d561` following that, to show response.

last one:
```
{“name":"S3","bucketName":"bigmpu-test-bucket-1486497345481","objectKey":"mpuKey","bytesReceived":868993,"bodyLength":868993,"setting":"yes","time":1486497683362,"req_id":"c3147cb276279110d561","level":"info","message":"MPU_TESTING env variable setting","hostname":"box5","pid":122}
```

Instead new request shows up:
```
{“name":"S3","clientIP":"::ffff:172.17.0.2","clientPort":60373,"httpMethod":"POST","httpURL":"/bigmpu-test-bucket-1486497345481/mpuKey?uploadId=eee72e77c5bf451fbb42d21a6204217a","time":1486497801878,"req_id":"62d6341c27397ed481e2","level":"info","message":"received request","hostname":"box5","pid":128}
```

`storedPartsAsObjects` starts with: 
```
[
    {
        "key": "eee72e77c5bf451fbb42d21a6204217a..|..05249",
        "ETag": "\"900150983cd24fb0d6963f7d28e17f72\"",
        "size": 3,
        "locations": [
            {
                "key": "EC15B39EF1FC06A5C286B16B87A31159563D7320",
                "dataStoreName": "sproxyd"
            }
        ]
    },
```

This is the one that fails. Ends with:
```
    {
        "key": "eee72e77c5bf451fbb42d21a6204217a..|..10000",
        "ETag": "\"900150983cd24fb0d6963f7d28e17f72\"",
        "size": 3,
        "locations": [
            {
                "key": "C01F7937EC7E33A7C286B16B87A3115988E3DC20",
                "dataStoreName": "sproxyd"
            }
        ]
    }
]
===========================
Cannot have more parts in complete message than were put
partLength (10000 > storedPartsAsObjects.length (4752)
===========================
{"name":"S3","bucketName":"bigmpu-test-bucket-1486497345481","objectKey":"mpuKey","bytesReceived":868993,"bodyLength":868993,"bytesSent":327,"clientIP":"::ffff:172.17.0.2","clientPort":60373,"httpMethod":"POST","httpURL":"/bigmpu-test-bucket-1486497345481/mpuKey?uploadId=eee72e77c5bf451fbb42d21a6204217a","httpCode":400,"time":1486497803067,"req_id":"62d6341c27397ed481e2","elapsed_ms":1188.636684,"level":"info","message":"responded with error XML","hostname":"box5","pid":128}`
```

Then, the delete requests:
```
{“name":"S3","clientIP":"::ffff:172.17.0.2","clientPort":32957,"httpMethod":"DELETE","httpURL":"/bigmpu-test-bucket-1486497345481/mpuKey","time":1486497803094,"req_id":"9ccad72a1b2e7cf6fd2e","level":"info","message":"received request","hostname":"box5","pid":116}
```

**Comment by electrachong** [comment]
Discussed with Lauren, a possible interpretation is the sdk is sending the complete mpu request twice because the first one takes so long to send a response (a retry). In the meantime, the second request starts after some of the uploaded parts have been deleted, causing it to fail.

Along this hypothesis, I am running end-to-ends again with the sdk configured to wait longer to retry.
end-to-end: http://ci.ironmann.io/gh/scality/Integration/9387

**Comment by electrachong** [comment]
Increased to retry delay base to 10 seconds, another end-to-end: http://ci.ironmann.io/gh/scality/Integration/9390

**Comment by electrachong** [comment]
Previous end-to-end succeeded.
Adding a time elapsed statement to calculate how long it takes to complete mpu:
http://ci.ironmann.io/gh/scality/Integration/9393

**Comment by electrachong** [comment]
latest attempt, with a retry delay base of 10000 ms:
```
completempu time elapsed: 121379 ms

    1) should intiate, put parts and complete mpu with 10,000 parts

    2) "after all" hook for "should intiate, put parts and complete mpu with 10,000 parts"

  0 passing (8m)

  2 failing
```

**Comment by electrachong** [comment]
Another end-to-end...
http://ci.ironmann.io/gh/scality/Integration/9402

However, it doesn't look likely altering the retry delay base is the solution, since I changed it to 50 ms (instead of default 100 ms) in https://github.com/scality/S3/pull/599 and that branch passed one of the end-to-ends. It's unlikely the time it takes to complete a mpu varies that much that it would be less than 50 ms in one try and more than 10 s in another. I'm revisiting the logs trying to see if I can spot anything else, in the meantime, this end to end is running.

**Comment by electrachong** [comment]
another end to end with retries disabled all-together: http://ci.ironmann.io/gh/scality/Integration/9403

**Comment by electrachong** [comment]
success with retry delay base of 600000 ms for 9402:
```
completempu time elapsed: 31770 ms

    ✓ should intiate, put parts and complete mpu with 10,000 parts (372960ms)

  1 passing (6m)
```

**Comment by electrachong** [comment]
end-to-end for disabled retries keep failing due to seemingly irrelevant build / circle ci issues, here is a fresh one:
http://ci.ironmann.io/gh/scality/Integration/9411

**Comment by electrachong** [comment]
note that the test passed in an end-to-end for another branch where I disabled retries:
http://ci.ironmann.io/gh/scality/Integration/9409

**Comment by electrachong** [comment]
result from last end-to-end, with disabled retries:
```
  0 passing (8m)

  2 failing

  1) large mpu should intiate, put parts and complete mpu with 10,000 parts:

     NetworkingError: socket hang up

      at createHangUpError (_http_client.js:213:15)

      at TLSSocket.socketOnEnd (_http_client.js:305:23)

      at endReadableNT (_stream_readable.js:921:12)

  2) large mpu "after all" hook for "should intiate, put parts and complete mpu with 10,000 parts":

     MPUinProgress: The bucket you tried to delete has an ongoing multipart upload.

      at Request.extractError (/home/scality/S3/node_modules/aws-sdk/lib/services/s3.js:323:35)

      at Request.callListeners (/home/scality/S3/node_modules/aws-sdk/lib/sequential_executor.js:105:20)

      at Request.emit (/home/scality/S3/node_modules/aws-sdk/lib/sequential_executor.js:77:10)

      at Request.emit (/home/scality/S3/node_modules/aws-sdk/lib/request.js:595:14)

      at Request.transition (/home/scality/S3/node_modules/aws-sdk/lib/request.js:21:10)

      at AcceptorStateMachine.runTo (/home/scality/S3/node_modules/aws-sdk/lib/state_machine.js:14:12)

      at /home/scality/S3/node_modules/aws-sdk/lib/state_machine.js:26:10

      at Request.<anonymous> (/home/scality/S3/node_modules/aws-sdk/lib/request.js:37:9)

      at Request.<anonymous> (/home/scality/S3/node_modules/aws-sdk/lib/request.js:597:12)

      at Request.callListeners (/home/scality/S3/node_modules/aws-sdk/lib/sequential_executor.js:115:18)

      at Request.emit (/home/scality/S3/node_modules/aws-sdk/lib/sequential_executor.js:77:10)

      at Request.emit (/home/scality/S3/node_modules/aws-sdk/lib/request.js:595:14)

      at Request.transition (/home/scality/S3/node_modules/aws-sdk/lib/request.js:21:10)

      at AcceptorStateMachine.runTo (/home/scality/S3/node_modules/aws-sdk/lib/state_machine.js:14:12)

      at /home/scality/S3/node_modules/aws-sdk/lib/state_machine.js:26:10

      at Request.<anonymous> (/home/scality/S3/node_modules/aws-sdk/lib/request.js:37:9)

      at Request.<anonymous> (/home/scality/S3/node_modules/aws-sdk/lib/request.js:597:12)

      at Request.callListeners (/home/scality/S3/node_modules/aws-sdk/lib/sequential_executor.js:115:18)

      at callNextListener (/home/scality/S3/node_modules/aws-sdk/lib/sequential_executor.js:95:12)

      at IncomingMessage.onEnd (/home/scality/S3/node_modules/aws-sdk/lib/event_listeners.js:208:11)

      at endReadableNT (_stream_readable.js:921:12)

    2) "after all" hook for "should intiate, put parts and complete mpu with 10,000 parts"

  0 passing (8m)

  2 failing
```
So it does look like the retry caused the InvalidPart error, but we still have an issue with completeMpus not always returning a response in a timely manner...

**Comment by electrachong** [comment]
First log from above end-to-end with completempu requestId has timestamp of 1486519601570. 
```
{"name":"S3","clientIP":"::ffff:172.17.0.2","clientPort":52949,"httpMethod":"POST","httpURL":"/bigmpu-test-bucket-1486519265912/mpuKey?uploadId=40faddd25d8d44d1a5c11d5812d72298","time":1486519601570,"req_id":"dd1a48c6a5e8cdb50f6a","level":"info","message":"received request","hostname":"box7","pid":127}
```
Last log has timestamp of 1486519602876.
```
{"name":"S3","bucketName":"bigmpu-test-bucket-1486519265912","objectKey":"mpuKey","bytesReceived":868993,"bodyLength":868993,"setting":"yes","time":1486519602876,"req_id":"dd1a48c6a5e8cdb50f6a","level":"info","message":"MPU_TESTING env variable setting","hostname":"box7","pid":127}
```
Difference is 1306 ms.

Need to figure out where request is being dropped or getting tied up after that point.

**Comment by electrachong** [comment]
end-to-end with lots of console logs to try and figure out where request gets tied up:
http://ci.ironmann.io/gh/scality/Integration/9413

**Comment by electrachong** [comment]
testing to see if recent build failures are related to last commit by rolling back one: http://ci.ironmann.io/gh/scality/Integration/9418

**Comment by electrachong** [comment]
build passed: http://ci.ironmann.io/gh/scality/Integration/9432

Retrying to see if we can capture failure:
http://ci.ironmann.io/gh/scality/Integration/9435

**Comment by electrachong** [comment]
Closing PR for now as past five builds have passed the failing test, keeping branch & can re-open to test further if test still encounters problems in builds.

**Comment by electrachong** [comment]
word came of a build in another branch failing this test with the socket hang-up error
rebased onto master and running an end-to-end:
http://ci.ironmann.io/gh/scality/Integration/9460

**Comment by electrachong** [comment]
new day:
http://ci.ironmann.io/gh/scality/Integration/9489

**Comment by nicolas2bert** [comment]
UTAPI failure from yesterday was probably because Integration forward port rel/6.4 to master: scality/Integration#446 was not merged yet :)
Should work today :)

**Comment by electrachong** [comment]
new end-to-end, more console.logs
http://ci.ironmann.io/gh/scality/Integration/9494

**Comment by electrachong** [comment]
end-to-end with more console.logs, node timeout set to 600000 ms:
http://ci.ironmann.io/gh/scality/Integration/9505

**Pull request closed without merging**
