### PR TITLE
Rf/hacky subpart trick

### PR DESCRIPTION
**Pull request by electrachong**
Depends on https://github.com/scality/Arsenal/pull/385

We should now be able to reliably calculate how many subparts we store based on total size of part

### CODE REVIEW

**Comment by electrachong** [comment]
@ironman-machine 
SCALITY_ARSENAL_BRANCH=https://github.com/scality/Arsenal/pull/385
try

**Comment by electrachong** [comment]
@ironman-machine 
SCALITY_ARSENAL_BRANCH=rf/azure-hacky-subpart-trick
try

**Comment by electrachong** [comment]
end to end auto-retried and passed here: http://ci.ironmann.io/gh/scality/Integration/17748#build-parameters

**Comment by rahulreddy** [comment]
@ironman-machine 
clean
r=76dfff9
after=https://github.com/scality/Arsenal/pull/385

**Comment by rahulreddy** [comment]
@ironman-machine 
r-
clean
r=76dfff9

**Comment by rahulreddy** [comment]
@ironman-machine r-

**Comment by rahulreddy** [comment]
Merging this. It was passing originally with the dropme commit.

**Pull request merged**
