### PR TITLE
Use Arsenal Auth

### LINKED ISSUE #76: Use Arsenal auth implementation
It was extracted from S3 for Vault's need, and we need to use it ASAP to reduce code duplication and maintenance pain.

### PR DESCRIPTION
**Pull request by DavidPineauScality**
Use Arsenal's auth implementation.

The auth implementation in arsenal was originally a copy of the one located in
lib/auth. The API is not cleaned-up at the moment, and as such, some parts of
the code look leaky (abstraction/concerns separation). This will be cleaned-up
at a later date.

Since we're now using Arsenal's implementation, we're also deleting all the
auth computation code from lib/auth, along with the associated tests.

Fixes #76

Depends on https://github.com/scality/Arsenal/pull/101

### CODE REVIEW

**Comment by DavidPineauScality** [comment]
@ironman-machine time to work

**Comment by DavidPineauScality** [comment]
End-to-end tests are passing :)

**Comment by michael-zapata** [comment]
Dat diff. :racehorse: :+1:

**Comment by vrancurel** [comment]
👍

**Comment by DavidPineauScality** [comment]
@LaurenSpiegel Once Arsenal#101 is merged , don't forget to remove the dropme commit before merging this one :)

**Pull request merged**
