### PR TITLE
Fix/v2 expiryrel1

### PR DESCRIPTION
**Pull request by LaurenSpiegel**
Extends time for v2 query auth expiration to 60 minutes and 1 second.

### CODE REVIEW

**Comment by LaurenSpiegel** [comment]
@ironman-machine check it

**Comment by rahulreddy** [comment]
👍

**Comment by LaurenSpiegel** [comment]
@ironman-machine hello
SCALITY_FEDERATION_BRANCH=rel/ga/1.0

**Comment by LaurenSpiegel** [comment]
@ironman-machine come on
SCALITY_FEDERATION_BRANCH=rel/ga/1.0
SCALITY_INTEGRATION_BRANCH=wip/ultron-ansible20

**Comment by RachedBenMustapha** [comment]
👍

**Pull request merged**
