### PR TITLE
FT: Add push metrics for more routes

### PR DESCRIPTION
**Pull request by rahulreddy**
This commit adds push metrics support on bucket level for
 - Initiate Multipart Upload
 - Complete Multipart Upload
 - Abort Multipart Upload
 - Head Bucket
 - Head Object

### CODE REVIEW

**Comment by rahulreddy** [comment]
**https://github.com/scality/utapi/pull/13  needs to be merged before this**

**Comment by LaurenSpiegel** [comment]
👍

**Comment by rahulreddy** [comment]
Utapi#13 is merged, removed the drop me commit

**Comment by RachedBenMustapha** [comment]
👍

**Pull request merged**
