### PR TITLE
Fwdport 7.2 to rel/7.4 (formerly master)

### PR DESCRIPTION
**Pull request by ThibaultRiviere**
# Pull request template

### Motivation and context

Why is this change required? What problem does it solve?

### Related issues

Please use the following link syntaxes #600 to reference issues in the
current repository

### Add tests to cover the changes

New tests added or existing tests modified to cover all changes

### Sign your work

In order to contribute to the project, you must sign your work
https://github.com/scality/Guidelines/blob/master/CONTRIBUTING.md#sign-your-work

Thank you again for contributing! We will try to test and integrate the change
as soon as we can.

### CODE REVIEW

**Comment by DavidPineauScality** [comment]
@bennettbuchanan any idea why this constantly fails on some Azure tests ? I can't understand what's failing from the change, but the error seems to be constant.

**Comment by bennettbuchanan** [comment]
@DavidPineauScality Looks like `getAzureContainerName` is missing a param that was added in master but is reverted here. https://github.com/scality/S3/pull/1092/files#diff-259359774bc4a7a93a170e43719bba53R8

**Comment by DavidPineauScality** [comment]
@bennettbuchanan Thanks :D !

**Comment by DavidPineauScality** [comment]
Suceeded at https://github.com/scality/Integration/pull/631#issuecomment-362599961

**Comment by DavidPineauScality** [comment]
Merging synchronously scality/bucketclient#128 scality/S3#1092 scality/MetaData#1317 scality/sproxydclient#136 scality/Arsenal#404 scality/backbeat#170 scality/Integration#631 , scality/Federation#1310

**Pull request merged**
