### PR TITLE
backport to rel/7.0: missing mpu bucket prefix [S3C-632]

### PR DESCRIPTION
**Pull request by electrachong**
(cherry picked from commit 2fb0b6855a541dfa3242ea2515ec5e1d7fe7cddf)

I think we should backport this fix to rel/7.0 since the release was affected by this bug as well.

### CODE REVIEW

**Comment by electrachong** [comment]
@ironman-machine

**Comment by electrachong** [comment]
end-to-end passed (I think regular ci tests are failing because they are not run with rel/7.0 arsenal branch)

**Comment by rahulreddy** [comment]
Wasn't the bug introduced when the routes were extracted in Arsenal which was after the 7.0 release? If yes, why do we need this to be backported?

**Comment by electrachong** [comment]
I think it was merged before the 7.0 release / branch was created:
https://github.com/scality/S3/commits/rel/7.0

**Comment by electrachong** [comment]
@ironman-machine after locking dependency pakages

**Comment by electrachong** [comment]
end to end passed, altho regular ci is still failing (I guess this time because of cache..)

**Pull request merged**
