### PR TITLE
Forward-port of rel/1.1-smartbulb into master

### PR DESCRIPTION
**Pull request by DavidPineauScality**
The forward-port of rel/1.1 to rel/1.1-smartbulb was already done, so here is the step that will bring all the required changes to master.

As there were a few conflicts, @rahulreddy @LaurenSpiegel Could you please check this over, and validate that everything's good here ? We'll run the end-to-end CI anyways.

Once this is merged, people should automatically forward-port their changes from one branch to another (reminder, at the moment the order is:  rel/1.1 -> rel/1.1-smartbulb -> master)

### CODE REVIEW

**Comment by DavidPineauScality** [comment]
@ironman-machine If you can validate that ... :)

**Comment by LaurenSpiegel** [comment]
👍

**Comment by DavidPineauScality** [comment]
end-to-end passed, which is a good news :)

**Comment by rahulreddy** [comment]
👍

**Pull request merged**
