### PR TITLE
ft: Add proxy support for Azure data backend

### PR DESCRIPTION
**Pull request by dora-korpar**

### CODE REVIEW

**Comment by dora-korpar** [comment]
@ironman-machine try

**Comment by dora-korpar** [comment]
@ironman-machine try

**Comment by dora-korpar** [comment]
@ironman-machine try

**Comment by rahulreddy** [comment]
@ironman-machine r-

**Comment by rahulreddy** [comment]
@ironman-machine try

**Comment by dora-korpar** [comment]
@ironman-machine try

**Pull request merged**
