### PR TITLE
COMPAT: website - Error HTML response

### LINKED ISSUE #565: COMPAT: Website - Error HTML response
AWS does not use id Attribute `id='code'` / `id='message'` in the error HTML response.

AWS:
```
<html>
   <head>
      <title>404 Not Found</title>
   </head>
   <body>
      <h1>404 Not Found</h1>
      <ul>
         <li>Code: NoSuchBucket</li>
         <li>Message: The specified bucket does not exist</li>
         <li>BucketName: bucket-490bp1gikzgmr8q9lb9svi-</li>
         <li>RequestId: 0D59AEE1CB97BA03</li>
         <li>HostId: Xm0aXGpPL2QVwdtmC/EHQCryPTN/NH6nKka3PGIGrBS8TPBbZlCRAUzH7OusziC6RHLg+1mRmM0=</li>
      </ul>
      <hr/>
   </body>
</html>
```

S3 server:

```
<html>
   <head>
      <title>404 Not Found</title>
   </head>
   <body>
      <h1>404 Not Found</h1>
      <ul>
         <li id='code'>Code: NoSuchBucket</li>
         <li id='message'>Message: The specified bucket does not exist.</li>
         <li>BucketName: bucketwebsitetester</li>
         <li>RequestId: 01e3e3416c720381e544</li>
      </ul>
      <hr>
   </body>
</html>
```

### PR DESCRIPTION
**Pull request by nicolas2bert**
FIXES #565 

This change fixes couple s3_website Ceph tests.
These tests are also going to be added in the CI.

### CODE REVIEW

**Comment by nicolas2bert** [comment]
@ironman-machine ok

**Comment by LaurenSpiegel** [comment]
Let's put this in 6.4 and please run end to end

**Comment by nicolas2bert** [comment]
@ironman-machine try

**Comment by nicolas2bert** [comment]
http://ci.ironmann.io/gh/scality/Integration/9148

**Pull request merged**
