### PR TITLE
ZENKO-89 Ft/mongo search

### PR DESCRIPTION
**Pull request by vrancurel**
- Parse a SQL Where statement into an AST
- validate the AST against regular fields
- transform the AST into Mongo query fields
- Perform the query

### CODE REVIEW

**Comment by vrancurel** [comment]
@ironman-machine r+

**Comment by vrancurel** [comment]
@ironman-machine try

**Comment by LaurenSpiegel** [comment]
@ironman-machine try

**Comment by LaurenSpiegel** [comment]
@ironman-machine try

**Comment by vrancurel** [comment]
@ironman-machine try

**Pull request merged**
