### PR TITLE
Fail healthchecks if any on multiple data backends fail

### PR DESCRIPTION
**Pull request by dora-korpar**
Fixes S3 not returning error on failing healthcheck in any of multiple data backends

### CODE REVIEW

**Comment by dora-korpar** [comment]
@ironman-machine try

**Comment by dora-korpar** [comment]
@ironman-machine try

**Comment by dora-korpar** [comment]
@ironman-machine try

**Comment by dora-korpar** [comment]
@ironman-machine try

**Comment by dora-korpar** [comment]
@ironman-machine try

**Comment by LaurenSpiegel** [comment]
end to end passed: http://ci.ironmann.io/gh/scality/Integration/11562

**Pull request merged**
