### PR TITLE
Perf: improvment

### PR DESCRIPTION
**Pull request by alexandre-merle**
- Send the request logger to bucketclient
  instead create a new one each request

### CODE REVIEW

**Comment by alexandre-merle** [comment]
@ironman-machine go

SCALITY_VAULT_BRANCH=perf/improvment
SCALITY_METADATA_BRANCH=perf/improvment

**Comment by MathieuCassagne** [comment]
:+1:

**Comment by ThibaultRiviere** [comment]
@ironman-machine  can i merge the scality/bucketclient#79 ?

**Comment by rahulreddy** [comment]
👍

**Pull request closed without merging**
