### PR TITLE
FT: Node v6

### PR DESCRIPTION
**Pull request by alexandre-merle**
Switch to node v6

### CODE REVIEW

**Comment by LaurenSpiegel** [comment]
what about this?  https://github.com/scality/S3/issues/249

**Comment by alexandre-merle** [comment]
@LaurenSpiegel still not start to work on this :) We have node v6 with binary encryption everywhere for the moment :)

**Comment by LaurenSpiegel** [comment]
please update readme as well and have lots of end to end fun :)

**Comment by LaurenSpiegel** [comment]
Once this is forward ported to master, the update will have to be made in this branch: https://github.com/scality/S3/pull/591/files#diff-c945a46d13b34fcaff544d966cffcabaR162

**Comment by alexandre-merle** [comment]
@LaurenSpiegel updated :)

**Comment by LaurenSpiegel** [comment]
The readme too...

**Comment by alexandre-merle** [comment]
@LaurenSpiegel damn ^^ will modify it ^^

**Comment by alexandre-merle** [comment]
updated :)

**Comment by alexandre-merle** [comment]
@ironman-machine 
SCALITY_METADATA_BRANCH=ft/node-v6
SCALITY_INTEGRATION_BRANCH=ft/node-v6
SCALITY_VAULT_BRANCH=ft/node-v6
try

**Comment by LaurenSpiegel** [comment]
Thank you, @alexandre-merle!!

**Pull request merged**
