### PR TITLE
FIX: Prevent unlimited setting of event listeners

### PR DESCRIPTION
**Pull request by LaurenSpiegel**
Fixes https://github.com/scality/S3/issues/271

### CODE REVIEW

**Comment by LaurenSpiegel** [comment]
@vrancurel, this prevents the memory leak warnings.  Thoughts?

**Comment by GiorgioRegni** [comment]
@vrancurel what do you think of this patch?

**Comment by MathieuCassagne** [comment]
@LaurenSpiegel: What about using the ```removeAllListeners``` before putting a new one ?
https://nodejs.org/dist/latest-v4.x/docs/api/events.html#events_emitter_removealllisteners_eventname
I'm not sure what is the cleanest way :s

**Comment by LaurenSpiegel** [comment]
@MathieuCassagne, I tried that any many other permutations.  If I remember correctly, if you removeAllListeners or just limit to one altogether, you end up freezing.  Rahul had a different fix that set the listeners outside the function so they wouldn't keep getting set, but that significantly impacted performance.

**Comment by rahulreddy** [comment]
@MathieuCassagne Removing all listeners would have an adverse affect as there would be more events emitted and less listeners listening to them.
This https://github.com/scality/S3/commit/100226a4205daa9545d73c5dd7b3b1c2b62b6c10 would be the clean way of implementing it but it made the tests run significantly longer.

**Comment by vrancurel** [comment]
The event.emit() is synchronous, causing a 'stack' overflow in case of heavy concurrency. Isn't it enough to just call event.emit() from a process.nextTick() lines 121 and 176 ?

**Comment by LaurenSpiegel** [comment]
@vrancurel, I just tested inserting the process.nextTicks and it does not prevent the memory leak from the addition of the listeners.  Is my change palatable?

**Comment by LaurenSpiegel** [comment]
After discussing with @vrancurel, he approves.  Merging.

**Pull request merged**
