### PR TITLE
rf: moving backends to Arsenal

### PR DESCRIPTION
**Pull request by JianqinWang**
Extracting metadata backends to Arsenal for use in backbeat
https://github.com/scality/Arsenal/pull/425 needs to be merged first.
JIRA: https://scality.atlassian.net/browse/ZENKO-140

### CODE REVIEW

**Comment by rahulreddy** [comment]
@ironman-machine try

**Comment by rahulreddy** [comment]
@ironman-machine try

**Comment by JianqinWang** [comment]
@ironman-machine try

**Comment by JianqinWang** [comment]
@ironman-machine try

**Comment by JianqinWang** [comment]
@ironman-machine try

**Comment by JianqinWang** [comment]
@ironman-machine try

**Comment by JianqinWang** [comment]
@ironman-machine try

**Pull request merged**
