### PR TITLE
Fix/disable large mpu retry

### PR DESCRIPTION
**Pull request by electrachong**
Review https://github.com/scality/S3/commit/2284dd9e7b605586b9eb1eb2b246f0f575ccfde7 only, the code change accidentally made its way into the previous commit.

FIXES scality/Integration#449

### CODE REVIEW

**Comment by electrachong** [comment]
end-to-end: http://ci.ironmann.io/gh/scality/Integration/9444

**Comment by electrachong** [comment]
@bennettbuchanan The commit actually disables retries, so it should not fail due to a retry.
However, the test may still fail if it takes too long to respond and hangs up the socket. I added a comment to reference the current issue. Let me know if it's clear to you.

**Comment by bennettbuchanan** [comment]
Ah, I had assumed that if it got to the point of needing to retry the test, then it means the test is failed instead of letting it retry repeatedly. 

It sounds like it would be clear that the request was taking too long.

**Comment by electrachong** [comment]
@bennettbuchanan Oh, OK, I think I get what you mean about the original comment being ambiguous. The retry was actually causing the test to fail because the first complete mpu request would delete some stored parts by the time the second request is sent by aws-node-sdk, and that's why we disabled it. I clarified the retry may cause the test to fail.

**Pull request merged**
